// Automatically generated package.
package val

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 95a5cf31a385d91b952e19190af5a828d2e60ed8

import (
	"github.com/Kyagara/equinox/internal"
)

// Note: this struct is automatically generated.
type VALClient struct {
	internalClient  *internal.InternalClient
	ContentV1  *ContentV1
	MatchV1  *MatchV1
	RankedV1  *RankedV1
	StatusV1  *StatusV1
}

// Creates a new VALClient using the InternalClient provided.
func NewVALClient(client *internal.InternalClient) *VALClient {
	return &VALClient{
        internalClient: client,
        ContentV1: &ContentV1{internalClient: client},
        MatchV1: &MatchV1{internalClient: client},
        RankedV1: &RankedV1{internalClient: client},
        StatusV1: &StatusV1{internalClient: client},
	}
}
