// This package is used to interact with all VALORANT endpoints.
//   - ContentV1
//   - MatchV1
//   - RankedV1
//   - StatusV1
//
// Note: this package is automatically generated.
package val

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = b554b42a14de337810d5a510d533453eaf6de207

import "github.com/Kyagara/equinox/internal"

// Note: this struct is automatically generated.
type VALClient struct {
	internalClient *internal.InternalClient
	ContentV1      *ContentV1
	MatchV1        *MatchV1
	RankedV1       *RankedV1
	StatusV1       *StatusV1
}

// Creates a new VALClient using the InternalClient provided.
func NewVALClient(client *internal.InternalClient) *VALClient {
	return &VALClient{
		internalClient: client,
		ContentV1:      &ContentV1{internalClient: client},
		MatchV1:        &MatchV1{internalClient: client},
		RankedV1:       &RankedV1{internalClient: client},
		StatusV1:       &StatusV1{internalClient: client},
	}
}
