// This package is used to interact with all TFT endpoints.
//   - SpectatorV5
//   - LeagueV1
//   - MatchV1
//   - StatusV1
//   - SummonerV1
//
// Note: this package is automatically generated.
package tft

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 92f57e3e7279cc02ec6a5ce6665ca08354d6a178

import "github.com/Kyagara/equinox/v2/internal"

type Client struct {
	SpectatorV5 SpectatorV5
	LeagueV1    LeagueV1
	MatchV1     MatchV1
	StatusV1    StatusV1
	SummonerV1  SummonerV1
}

// Creates a new TFT Client using the internal.Client provided.
func NewTFTClient(client *internal.Client) *Client {
	return &Client{
		SpectatorV5: SpectatorV5{internal: client},
		LeagueV1:    LeagueV1{internal: client},
		MatchV1:     MatchV1{internal: client},
		StatusV1:    StatusV1{internal: client},
		SummonerV1:  SummonerV1{internal: client},
	}
}
