// This package is used to interact with all TFT endpoints.
//   - LeagueV1
//   - MatchV1
//   - StatusV1
//   - SummonerV1
//
// Note: this package is automatically generated.
package tft

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 48735a0c9d1c521d94a20ff0b0b9dc927ab430ca

import "github.com/Kyagara/equinox/internal"

type Client struct {
	LeagueV1   LeagueV1
	MatchV1    MatchV1
	StatusV1   StatusV1
	SummonerV1 SummonerV1
}

// Creates a new TFT Client using the internal.Client provided.
func NewTFTClient(client *internal.Client) *Client {
	return &Client{
		LeagueV1:   LeagueV1{internal: client},
		MatchV1:    MatchV1{internal: client},
		StatusV1:   StatusV1{internal: client},
		SummonerV1: SummonerV1{internal: client},
	}
}
