package tft

import "strconv"

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 6461993a9c4165ddca053929f19f6d0e3eb1ca14

// Platform routes for League of Legends and Teamfight Tactics.
type PlatformRoute string

const (
	// Brazil.
	BR1 PlatformRoute = "br1"
	// Europe, Northeast.
	EUN1 PlatformRoute = "eun1"
	// Europe, West.
	EUW1 PlatformRoute = "euw1"
	// Japan.
	JP1 PlatformRoute = "jp1"
	// Korea.
	KR PlatformRoute = "kr"
	// Latin America, North.
	LA1 PlatformRoute = "la1"
	// Latin America, South.
	LA2 PlatformRoute = "la2"
	// North America.
	NA1 PlatformRoute = "na1"
	// Oceania.
	OC1 PlatformRoute = "oc1"
	// Public Beta Environment, special beta testing platform. Located in North America.
	PBE1 PlatformRoute = "pbe1"
	// Philippines
	PH2 PlatformRoute = "ph2"
	// Russia
	RU PlatformRoute = "ru"
	// Singapore
	SG2 PlatformRoute = "sg2"
	// Thailand
	TH2 PlatformRoute = "th2"
	// Turkey
	TR1 PlatformRoute = "tr1"
	// Taiwan
	TW2 PlatformRoute = "tw2"
	// Vietnam
	VN2 PlatformRoute = "vn2"
)

func (route PlatformRoute) String() string {
	switch route {
	case BR1:
		return "br1"
	case EUN1:
		return "eun1"
	case EUW1:
		return "euw1"
	case JP1:
		return "jp1"
	case KR:
		return "kr"
	case LA1:
		return "la1"
	case LA2:
		return "la2"
	case NA1:
		return "na1"
	case OC1:
		return "oc1"
	case PBE1:
		return "pbe1"
	case PH2:
		return "ph2"
	case RU:
		return "ru"
	case SG2:
		return "sg2"
	case TH2:
		return "th2"
	case TR1:
		return "tr1"
	case TW2:
		return "tw2"
	case VN2:
		return "vn2"
	default:
		return string(route)
	}
}

// League of Legends and Teamfight Tactics ranked tiers, such as gold, diamond, challenger, etc.
type Tier string

const (
	IRON        Tier = "IRON"
	BRONZE      Tier = "BRONZE"
	SILVER      Tier = "SILVER"
	GOLD        Tier = "GOLD"
	PLATINUM    Tier = "PLATINUM"
	EMERALD     Tier = "EMERALD"
	DIAMOND     Tier = "DIAMOND"
	MASTER      Tier = "MASTER"
	GRANDMASTER Tier = "GRANDMASTER"
	CHALLENGER  Tier = "CHALLENGER"
)

func (tier Tier) String() string {
	switch tier {
	case IRON:
		return "IRON"
	case BRONZE:
		return "BRONZE"
	case SILVER:
		return "SILVER"
	case GOLD:
		return "GOLD"
	case PLATINUM:
		return "PLATINUM"
	case EMERALD:
		return "EMERALD"
	case DIAMOND:
		return "DIAMOND"
	case MASTER:
		return "MASTER"
	case GRANDMASTER:
		return "GRANDMASTER"
	case CHALLENGER:
		return "CHALLENGER"
	default:
		return string(tier)
	}
}

// League of Legends and Teamfight Tactics rank divisions, I, II, III, IV, and (deprecated) V.
type Division string

const (
	I   Division = "I"
	II  Division = "II"
	III Division = "III"
	IV  Division = "IV"
	// # Deprecated
	V Division = "V"
)

func (division Division) String() string {
	switch division {
	case I:
		return "I"
	case II:
		return "II"
	case III:
		return "III"
	case IV:
		return "IV"
	case V:
		return "V"
	default:
		return string(division)
	}
}

// League of Legends and Teamfight Tactics game types: matched game, custom game, or tutorial game.
type GameType string

const (
	// Custom games
	CUSTOM_GAME_GAMETYPE GameType = "CUSTOM_GAME"
	// all other games
	MATCHED_GAME_GAMETYPE GameType = "MATCHED_GAME"
	// Tutorial games
	TUTORIAL_GAME_GAMETYPE GameType = "TUTORIAL_GAME"
)

func (gameType GameType) String() string {
	switch gameType {
	case CUSTOM_GAME_GAMETYPE:
		return "CUSTOM_GAME"
	case MATCHED_GAME_GAMETYPE:
		return "MATCHED_GAME"
	case TUTORIAL_GAME_GAMETYPE:
		return "TUTORIAL_GAME"
	default:
		return string(gameType)
	}
}

// League of Legends and Teamfight Tactics ranked queue types.
type QueueType int32

const (
	// Ranked Teamfight Tactics (Double Up Workshop) games
	RANKED_TFT_DOUBLE_UP_QUEUETYPE QueueType = 1160
	// # Deprecated
	//
	// Ranked Teamfight Tactics (Double Up Workshop) games
	RANKED_TFT_PAIRS_QUEUETYPE QueueType = 1150
	// Ranked Teamfight Tactics games
	RANKED_TFT_QUEUETYPE QueueType = 1100
	// Ranked Teamfight Tactics (Hyper Roll) games
	RANKED_TFT_TURBO_QUEUETYPE QueueType = 1130
)

func (queueType QueueType) String() string {
	switch queueType {
	case RANKED_TFT_DOUBLE_UP_QUEUETYPE:
		return "1160"
	case RANKED_TFT_PAIRS_QUEUETYPE:
		return "1150"
	case RANKED_TFT_QUEUETYPE:
		return "1100"
	case RANKED_TFT_TURBO_QUEUETYPE:
		return "1130"
	default:
		return string(queueType)
	}
}

// League of Legends and Teamfight Tactics game modes, such as Classic,
// ARAM, URF, One For All, Ascension, etc.
type GameMode string

const (
	// Teamfight Tactics.
	TFT_GAMEMODE GameMode = "TFT"
)

func (gameMode GameMode) String() string {
	switch gameMode {
	case TFT_GAMEMODE:
		return "TFT"
	default:
		return string(gameMode)
	}
}

// League of Legends and Teamfight Tactics maps.
type Map int64

const (
	// Convergence
	//
	// Teamfight Tactics map
	CONVERGENCE_MAP Map = 22
)

func (lolMap Map) String() string {
	switch lolMap {
	case CONVERGENCE_MAP:
		return "22"
	default:
		return strconv.FormatInt(int64(lolMap), 10)
	}
}

// League of Legends and Teamfight Tactics queues.
type Queue int32

const (
	// # Deprecated
	//
	// Ranked Teamfight Tactics (Double Up Workshop) games on Convergence
	CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_1150_QUEUE Queue = 1150
	// Ranked Teamfight Tactics (Double Up Workshop) games on Convergence
	CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_QUEUE Queue = 1160
	// Ranked Teamfight Tactics (Hyper Roll) games on Convergence
	CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_HYPER_ROLL_QUEUE Queue = 1130
	// Ranked Teamfight Tactics games on Convergence
	CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_QUEUE Queue = 1100
	// Teamfight Tactics 1v0 games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_1V0_QUEUE Queue = 1091
	// Teamfight Tactics 2v0 games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_2V0_QUEUE Queue = 1092
	// Teamfight Tactics games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_QUEUE Queue = 1090
	// Teamfight Tactics Set 3.5 Revival games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_SET_3_5_REVIVAL_QUEUE Queue = 6000
	// Teamfight Tactics Simluation games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_SIMLUATION_QUEUE Queue = 1111
	// Teamfight Tactics Tutorial games on Convergence
	CONVERGENCE_TEAMFIGHT_TACTICS_TUTORIAL_QUEUE Queue = 1110
)

func (queue Queue) String() string {
	switch queue {
	case CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_1150_QUEUE:
		return "1150"
	case CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_DOUBLE_UP_WORKSHOP_QUEUE:
		return "1160"
	case CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_HYPER_ROLL_QUEUE:
		return "1130"
	case CONVERGENCE_RANKED_TEAMFIGHT_TACTICS_QUEUE:
		return "1100"
	case CONVERGENCE_TEAMFIGHT_TACTICS_1V0_QUEUE:
		return "1091"
	case CONVERGENCE_TEAMFIGHT_TACTICS_2V0_QUEUE:
		return "1092"
	case CONVERGENCE_TEAMFIGHT_TACTICS_QUEUE:
		return "1090"
	case CONVERGENCE_TEAMFIGHT_TACTICS_SET_3_5_REVIVAL_QUEUE:
		return "6000"
	case CONVERGENCE_TEAMFIGHT_TACTICS_SIMLUATION_QUEUE:
		return "1111"
	case CONVERGENCE_TEAMFIGHT_TACTICS_TUTORIAL_QUEUE:
		return "1110"
	default:
		return string(queue)
	}
}
