// This package is used to interact with all Riftbound endpoints.
//   - ContentV1
//
// Note: this package is automatically generated.
package riftbound

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 8fe5cbba355b369122ba6fca976ce8337698b578

import "github.com/Kyagara/equinox/v2/internal"

type Client struct {
	ContentV1 ContentV1
}

// Creates a new Riftbound Client using the internal.Client provided.
func NewRiftboundClient(client *internal.Client) *Client {
	return &Client{
		ContentV1: ContentV1{internal: client},
	}
}
