package riftbound

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 8fe5cbba355b369122ba6fca976ce8337698b578

import (
	"context"
	"net/http"
	"net/url"

	"github.com/Kyagara/equinox/v2/api"
	"github.com/Kyagara/equinox/v2/internal"
)

// # Riot API Reference
//
// [riftbound-content-v1]
//
// [riftbound-content-v1]: https://developer.riotgames.com/apis#riftbound-content-v1
type ContentV1 struct {
	internal *internal.Client
}

// Get riftbound content
//
// # Parameters
//   - route: Route to query.
//   - locale (optional): Defaults to en. Optional. Specifies the language and regional settings for the response. Use a locale code. During beta only en available.
//
// # Riot API Reference
//
// [riftbound-content-v1.getContent]
//
// [riftbound-content-v1.getContent]: https://developer.riotgames.com/api-methods/#riftbound-content-v1/GET_getContent
func (endpoint *ContentV1) Content(ctx context.Context, route api.RegionalRoute, locale string) (*ContentRiftboundContentV1DTO, error) {
	logger := endpoint.internal.Logger("Riftbound_ContentV1_Content")
	urlComponents := []string{"https://", route.String(), api.RIOT_API_BASE_URL_FORMAT, "/riftbound/content/v1/contents"}
	request, err := endpoint.internal.Request(ctx, logger, http.MethodGet, urlComponents, "riftbound-content-v1.getContent", nil)
	if err != nil {
		return nil, err
	}
	values := url.Values{}
	if locale != "" {
		values.Set("locale", locale)
	}
	request.Request.URL.RawQuery = values.Encode()
	var data ContentRiftboundContentV1DTO
	err = endpoint.internal.Execute(ctx, request, &data)
	if err != nil {
		return nil, err
	}
	return &data, nil
}
