// This package is used to interact with all Legends of Runeterra endpoints.
//   - DeckV1
//   - InventoryV1
//   - MatchV1
//   - RankedV1
//   - StatusV1
//
// Note: this package is automatically generated.
package lor

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 2099d6a309eb237d31b9c5fc1071c36eca85d91f

import "github.com/Kyagara/equinox/internal"

// Note: this struct is automatically generated.
type LORClient struct {
	DeckV1      *DeckV1
	InventoryV1 *InventoryV1
	MatchV1     *MatchV1
	RankedV1    *RankedV1
	StatusV1    *StatusV1
}

// Creates a new LORClient using the InternalClient provided.
func NewLORClient(client *internal.InternalClient) *LORClient {
	return &LORClient{
		DeckV1:      &DeckV1{internal: client},
		InventoryV1: &InventoryV1{internal: client},
		MatchV1:     &MatchV1{internal: client},
		RankedV1:    &RankedV1{internal: client},
		StatusV1:    &StatusV1{internal: client},
	}
}
