// Automatically generated package.
package riot

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 95a5cf31a385d91b952e19190af5a828d2e60ed8

import (
	"github.com/Kyagara/equinox/internal"
)

// Note: this struct is automatically generated.
type RiotClient struct {
	internalClient  *internal.InternalClient
	AccountV1  *AccountV1
}

// Creates a new RiotClient using the InternalClient provided.
func NewRiotClient(client *internal.InternalClient) *RiotClient {
	return &RiotClient{
        internalClient: client,
        AccountV1: &AccountV1{internalClient: client},
	}
}
