package riot

///////////////////////////////////////////////
//                                           //
//                     !                     //
//   This file is automatically generated!   //
//           Do not directly edit!           //
//                                           //
///////////////////////////////////////////////

// Spec version = 22eaf104ffa026981e6ecbf9bd5d60054f12ddf9

// account-v1.ActiveShardDto
type AccountActiveShardV1DTO struct {
	ActiveShard string `json:"activeShard,omitempty"`
	Game        string `json:"game,omitempty"`
	PUUID       string `json:"puuid,omitempty"`
}

// account-v1.AccountRegionDTO
type AccountRegionV1DTO struct {
	// Game to lookup active region
	Game string `json:"game,omitempty"`
	// Player Universal Unique Identifier. Exact length of 78 characters. (Encrypted)
	PUUID string `json:"puuid,omitempty"`
	// Player active region
	Region string `json:"region,omitempty"`
}

// account-v1.AccountDto
type AccountV1DTO struct {
	// This field may be excluded from the response if the account doesn't have a gameName.
	GameName string `json:"gameName,omitempty"`
	// Encrypted PUUID. Exact length of 78 characters.
	PUUID string `json:"puuid,omitempty"`
	// This field may be excluded from the response if the account doesn't have a tagLine.
	TagLine string `json:"tagLine,omitempty"`
}
