name: Continuous Integration

on:
    push:
        branches: '**'
        paths:
            - '**.go'
            - '.github/workflows/ci.yaml'
            - 'go.sum'
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install node dependencies
              run: npm ci --prefix srcgen

            - name: Run lint
              run: npm run lint --prefix srcgen

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20'
                  cache: false

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 18

            - name: Install node dependencies
              run: npm ci --prefix srcgen

            - name: Compiling clients
              run: npm run compile --prefix srcgen

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20'

            - name: Run tests
              run: go test ./... -v -race -coverprofile cover.out -covermode atomic

            - name: Run only DDragon/CDragon integration tests
              run: go test -v -tags=integration ./test/integration

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: ./cover.out
