name: Continuous integration

on:
    push:
        branches: '**'
        paths:
            - '**.go'
            - '.github/workflows/ci.yaml'
            - 'go.sum'
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20'
                  cache: false

            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest

            - name: Run go vet
              run: go vet ./...

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20'

            - name: Run tests
              run: go test ./... -v -race -coverprofile cover.txt -covermode atomic

            - name: Ensure integration tests build
              run: go test -v -tags=integration -run=^$ ./test/integration

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: ./cover.txt
