name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '>=1.20.0'
              run: go version

            - name: Verify dependencies
              run: go mod verify

            - name: Run go vet
              run: go vet ./...

            - name: Run go test
              run: go test ./... -v -race -coverprofile cover.txt -covermode atomic

            - name: Ensure integration tests build
              run: go test -v -tags=integration -run=^$ ./test/integration

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  files: ./cover.txt
