name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: go test ./... -v -coverprofile cover.txt -covermode atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./cover.txt
